# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 756e55fdf34d5ce6cb45a0712cb77f9892c9e1f644db4d83a0bf27f9eea0202b876c589642bf5a996183354bc4f41f3c850ccdeffc04b4e7a01b3b952fd84175

test:
  secret_key_base: 8cd99e91306375fe5f425e24fed8f7b58084639706310995c81cbe37743a31677d55e2b214e0761c85758d4e9f23d88da09fb17d557aa5140e35dc1dfd7d180b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
